name = "ColorBrewer"
uuid = "a2cac450-b92f-5266-8821-25eda20663c8"
license = "MIT"
desc = "A Julia library for generating color brewer color schemes"
authors = ["timothyrenner"]
version = "0.4.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
Colors = "0.12, 0.13"
JSON = "0.21"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
